#!/usr/bin/env bash

set -euo pipefail

cat > .env <<EOF
# ─── Airflow ───

AIRFLOW__CORE__EXECUTOR=LocalExecutor
AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
AIRFLOW__CORE__FERNET_KEY=
AIRFLOW__CORE__LOAD_EXAMPLES=False
AIRFLOW__WEBSERVER__SECRET_KEY=change_me

# ─── OpenSky Network API ───

OPENSKY_CLIENT_ID=${OPENSKY_CLIENT_ID}
OPENSKY_CLIENT_SECRET=${OPENSKY_CLIENT_SECRET}

# ─── Snowflake ───

SNOWFLAKE_ACCOUNT=${SNOWFLAKE_ACCOUNT}
SNOWFLAKE_USER=${SNOWFLAKE_USER}
SNOWFLAKE_PASSWORD=${SNOWFLAKE_PASSWORD}
SNOWFLAKE_WAREHOUSE=${SNOWFLAKE_WAREHOUSE}
SNOWFLAKE_DATABASE=${SNOWFLAKE_DATABASE}
SNOWFLAKE_SCHEMA=RAW
SNOWFLAKE_ROLE=ACCOUNTADMIN
EOF

chmod 600 .env

echo "✅ .env created successfully from GitHub Codespaces secrets."
